# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170717_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='GoodModel',
        ),
        migrations.RenameModel(
            old_name='Rewiev',
            new_name='ReviewModel',
        ),
    ]
