# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170717_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
