# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rewiev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=128)),
                ('mail', models.CharField(max_length=128)),
                ('theme', models.FloatField()),
                ('review', models.ImageField(upload_to='')),
                ('validated', models.BooleanField()),
            ],
        ),
    ]
