# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_good_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiev',
            name='review',
            field=models.CharField(max_length=512),
        ),
    ]
