# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170718_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='mail',
            new_name='reviewer_email',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='review',
            new_name='reviewer_text',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='validated',
        ),
    ]
