# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170718_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='reviewer_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 17, 12, 30, 705119, tzinfo=utc)),
        ),
    ]
