# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170718_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='reviewer_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
